// import { Inter } from "@next/font/google";
// const inter = Inter({ subsets: ["latin"] });
// import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { type NextPage } from "next";
import Head from "next/head";
import { BiCheck, BiUserPlus, BiUserX, BiX } from "react-icons/bi";
import { Form, Table } from "../components";
import { deleteUser, getUsers } from "../lib/helper";
import { deleteAction, toggleForm } from "../redux/features/toggleFormSlice";
import { useAppDispatch, useAppSelector } from "../redux/hooks";

const Home: NextPage = () => {
  const visible = useAppSelector((state) => state.toggleForm.visible);
  const deleteId = useAppSelector((state) => state.toggleForm.deleteId);
  const dispatch = useAppDispatch();

  const queryClient = useQueryClient();

  const handler = () => {
    dispatch(toggleForm());
  };

  const deletehandler = async () => {
    if (deleteId) {
      await deleteUser(deleteId);
      await queryClient.invalidateQueries(["users"]);
      await dispatch(deleteAction(null));
    }
  };

  const canclehandler = async () => {
    console.log("cancel");
    await dispatch(deleteAction(null));
  };

  return (
    <section>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-5">
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">Employee Management</h1>

        <div className="container mx-auto flex justify-between py-5 border-b">
          <div className="left flex gap-3">
            <button
              className="flex gap-2 bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-800"
              onClick={handler}
            >
              {visible ? "Close Form" : "Add Employee"}
              {visible ? <BiUserX size={23} /> : <BiUserPlus size={23} />}
            </button>
          </div>
          {deleteId ? DeleteComponent({ deletehandler, canclehandler }) : <></>}
        </div>

        {/* collapsible form */}
        {visible ? <Form /> : null}

        {/* table */}
        <div className="container mx-auto">
          <Table />
        </div>
      </main>
    </section>
  );
};

export default Home;

type DeleteComponentProps = {
  deletehandler: () => Promise<void>;
  canclehandler: () => Promise<void>;
};

function DeleteComponent({ deletehandler, canclehandler }: DeleteComponentProps) {
  return (
    <div className="flex gap-5">
      <button>Are you sure?</button>
      <button
        onClick={deletehandler}
        className="flex bg-red-500 text-white px-4 py-2 border rounded-md hover:bg-rose-500 hover:border-red-500 hover:text-gray-50"
      >
        Yes{" "}
        <span className="px-1">
          <BiX color="rgb(255 255 255)" size={25} />
        </span>
      </button>
      <button
        onClick={canclehandler}
        className="flex bg-green-500 text-white px-4 py-2 border rounded-md hover:bg-gree-500 hover:border-green-500 hover:text-gray-50"
      >
        No{" "}
        <span className="px-1">
          <BiCheck color="rgb(255 255 255)" size={25} />
        </span>
      </button>
    </div>
  );
}
